name: CI/CD flow for Dev branch
on: 
  push:
    branches:
      - dev
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout E2E code from a separate repo
        uses: actions/checkout@v3
        with:
          repository: tranvantoan-qn/todo-react-E2E-test
          path: cypress-tests

      - name: Install dependencies
        run: cd cypress-tests && npm install
      
      - name: Run tests
        run: cd cypress-tests && npx cypress open 
